name: 'Send Data to API using Docker'
description: 'A Docker-based GitHub Action to send data to a Node.js API endpoint'
inputs:
  api-url:
    description: 'API endpoint URL'
    required: true
  api-key:
    description: 'API key for authentication'
    required: true
  data:
    description: 'Data to be sent as JSON string'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_API_URL: ${{ inputs.api-url }}
    INPUT_API_KEY: ${{ inputs.api-key }}
    INPUT_DATA: ${{ inputs.data }}
